spring:
  application:
    name: LRMS
  datasource:
    url: jdbc:postgresql://localhost:5432/lrms
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    
jwt:
  secret: ${JWT_SECRET:8a2b5358c89c7d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c}
  expiration: 86400000

server:
  port: 8081
