spring:
  profiles:
    active: local
  application:
    name: LRMS
  datasource:
    url: jdbc:postgresql://localhost:5432/javasb
    username: ${DB_USER:postgres}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

server:
  port: 8081
